### ISSUE TITLE
Make dashboard editable

### ISSUE THREAD

**Issue by lucalas** [lucalas/StreamNode#3]
Make dashboard editable to allow people to reorder, hide, rename, etc.. the elements in the view.
We may need:

- Some Dashboard and cards changes based on card data (card visible, position, name)
- Make editable dashboard
- Implement websocket protocol between client and server to store edited dashboard information

**Comment by saliougaye** [comment]
Try this, I think it's what you need
https://www.npmjs.com/package/react-movable

**Comment by lucalas** [comment]
We have to try because I don't know if we can use react packages in Preact framework but I like it!

**Comment by saliougaye** [comment]
I find this for preact: https://www.npmjs.com/package/preact-moveable

**Comment by lucalas** [comment]
We can close this issue because of the pull request of @peppepol , thanks for the help.

**Comment by lucalas** [comment]
✔Some Dashboard and cards changes based on card data (card visible, position, name)
✔Make editable dashboard
❌Implement websocket protocol between client and server to store edited dashboard information

**Comment by lucalas** [comment]
✔Some Dashboard and cards changes based on card data (card visible, position, name)
✔Make editable dashboard
✔Implement websocket protocol between client and server to store edited dashboard information

We can close the issue.
